### ISSUE TITLE
Clarifications 

### ISSUE THREAD

**Issue by dvigneshwer** [rdegges/skele-cli#3]
@rdegges Thanks for the template and blog, its really great.

I have couple of doubts, which will be helpfull for people getting started with python packaging and CLI implementations:

## Testing 

* How is testing actually running ? Can you tell about the flow there ?

![image](https://cloud.githubusercontent.com/assets/5075497/20136553/83f88f7e-a69b-11e6-9b48-9ca8a6b019c9.png)

* The scripts inside the tests folder consists the testcases class for each functionality of the cli, where are these class's object being creted and called ?

You are using unittest package and not pytest (but the blog refers to pytest for testing)

![image](https://cloud.githubusercontent.com/assets/5075497/20136808/cd3a023e-a69c-11e6-84b6-7d1fb0e140a3.png)

## Packaging

* When we run the command pip install -e .[test] this implies that we are installing this package based on the setup.py configuration from the setuptools module, where does this package get installed (I see the package listed in the pip freeze command, but its location is not the dist-package location) 

* How do I install it as a actual package?

* How does the base class in main of cli.py get called and also when will the member function run() of base be called?

![image](https://cloud.githubusercontent.com/assets/5075497/20137394/28ef94ec-a6a0-11e6-9ca0-b86fb8a6faa0.png)

* How does this run as CLI tool ? 
* How does docopt module detect all the options ?

Thanks again

**Comment by rdegges** [comment]
Heyo!

I'm going to reply to some of these in here:

1. I'm using pytest as the test runner -- it can run normal python tests, there's no need to use the pytest API unnecessarily unless you really want to.
2. You can install the CLI tool for 'production' usage using a normal 'pip install' command once you've published your package to PyPI.

The other questions you asked are really out-of-scope of this tool. The purpose of this tool is just to give people a simple template for building python CLI tools, but isn't meant to be a full educational guide to packaging, testing, etc.

While I'd love to cover that stuff, each of those areas is a bunch of info on their own, and I just can't really include all of that in here or in that blog post.
