### ISSUE TITLE
Making a Cookiecutter CLI from this?

### ISSUE THREAD

**Issue by mindey** [rdegges/skele-cli#5]
The structure you introduced makes a lot of sense to me, and I would like it to work like a starter project to start with a Cookiecutter project initialization comand ( https://github.com/audreyr/cookiecutter ). Your article on https://stormpath.com/blog/building-simple-cli-interfaces-in-python actually creates a lot of value for novice, and makes things explicitly clear, so, I think it would make sense to include that description somewhere too.

**Comment by rdegges** [comment]
You're 100% welcome to create a cookiecutter project from this!
