### ISSUE TITLE
The command suggested won't work in .zsh

### ISSUE THREAD

**Issue by mindey** [rdegges/skele-cli#6]
I find that 

```
pip install -e .[test]
```

Works well in bash, but not in zsh...

```
$ pip install -e .[test]
zsh: no matches found: .[test]
```

**Comment by rdegges** [comment]
I actually use zsh myself. I run this command just fine all the time. =)

I'm using latest zsh (ubuntu) + oh-my-zsh. It also works fine on osx with zsh + oh-my-zsh.

What os / etc. are you using? I think this may actually be a different issue.

**Comment by shaddu** [comment]
I am using MacOS and it is giving same error and can't we build locally in virtualenv and test it over there ?

**Comment by rdegges** [comment]
What version of python / pip are you using? This works across Python 2.7+ from me testing right now (in ZSH) on both ubuntu 17 and OSX (latest).

This command IS building it in a virtualenv (or whatever environment you're in).

You can also do: `python setup.py install` if you want.

**Comment by shaddu** [comment]
I am using python 2.7 and for zsh python setup.py install worked but still i am not able to call my cli .can you please have look at my code once https://github.com/shaddu/hn-cli.

**Comment by rdegges** [comment]
Sorry :( Don't really have the time to analyze stuff like that. I apologize. I'm pretty crazy busy, always running behind ><
