### ISSUE TITLE
To know more

### ISSUE THREAD

**Issue by gitstercode** [rdegges/skele-cli#7]
Tutorial is working perfectly fine, I have question on the below command:

What actually the below command does:
`pip install -e .[test] `

I have following in requires.txt
```
docopt

[test]
coverage
pytest
pytest-cov
```
Also,  what all are required to setup environment for client users.
I mean anything that I can remove from requires.txt for client users environment?
I thank for the response in advance.

**Comment by rdegges** [comment]
Hi there.

This might actually be a better question for stackoverflow, sorry!
